---
# Expected results
interface:
  Ethernet1:
    duplex: "duplexFull"
    lineprotocol: "up"
    bandwidth: 100000000000
    neighbor: "{{ 'leaf01' + '.' + dns.domain }}"
    remote_port: "Ethernet1"
  Ethernet2:
    duplex: "duplexFull"
    lineprotocol: "up"
    bandwidth: 100000000000
    neighbor: "{{ 'leaf02' + '.' + dns.domain }}"
    remote_port: "Ethernet1"

bgp_neighbor:
  - BGP_NEIGH : "10.0.0.1"
    NEIGH_AS : "65001"
    STATE : "Estab"
    VRF: "default"

  - BGP_NEIGH : "10.0.0.3"
    NEIGH_AS : "65002"
    STATE : "Estab"
    VRF: "default"
